version: "3.8"
services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "8888:6379"
        networks:
            - default
    postgres:
        image: postgres:alpine
        container_name: 'postgres'
        ports:
            - 9999:5432
        volumes:
            - ./database/postgres:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: 123456
        networks:
            - default
networks:
    default:
        driver: bridge
