version: "3.8"
services:
   meuContainerApache:
      image: httpd:alpine
      container_name: 'meuContainerApache'
      ports:
         - 80:80
      volumes:
         - ./htdocs:/usr/local/apache2/htdocs/
      environment:
         - ROOT_PASSWORD=123456
      networks:
         - minhaConexaoPadrao
networks:
   minhaConexaoPadrao:
      driver: bridge